### ISSUE TITLE
Unused Record Fields

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/meandro#10]
# Rule
A rule to detect unused record fields.
The rule will detect fields defined as part of a record but never used anywhere.

### Note
This rule assumes that your code will never use the underlying tuple structure of your records directly.

# Example
```elixir
defmodule Rec do
  require Record
    Record.defrecord(:my_rec, used: :true, unused: :ok)
    def use(param) do
      my_rec(param, :used)
    end
end
```
Meandro should emit a warning about the `:unused`  field

**Comment by pablocostass** [comment]
PR #29 partially addressed this issue: it added a first approach that works on a per-module basis, but there is still the need to make the rule (i.e., the record usage tracking) work across modules
